services:
  limo_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: limo_dev
    platform: linux/arm64
    stdin_open: true
    tty: true
    environment:
      DISPLAY: host.docker.internal:0
      QT_X11_NO_MITSHM: "1"
      LIBGL_ALWAYS_INDIRECT: "1"
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      ROS_DOMAIN_ID: "${ROS_DOMAIN_ID:-21}"
    volumes:
      - .:/workspaces/limo_ws
    extra_hosts:
      - "host.docker.internal:host-gateway"
